language: node_js
os: linux
node_js:
  - "10"
services:
  - redis-server
jobs:
  include:
    - stage: testing
      if: branch in (develop)
      script:
        - npm install codecov -g
        - npm run test
      after_success:
        - mv coverage/coverage-final.json coverage/coverage.json
        - codecov
    - stage: npm release
      if: branch = master AND commit_message =~ /^[0-9]*\.[0-9]*\.[0-9]*$/
      before_deploy:
        - npm run build
      deploy:
        edge: true
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        cleanup: false
