language: node_js
os: linux
node_js:
  - "10"
services:
  - redis-server
jobs:
  include:
    - stage: testing
      if: branch in (develop)
    - stage: npm release
      if: branch = master AND commit_message =~ /^[0-9]*\.[0-9]*\.[0-9]*$/
      before_deploy:
        - npm run build
      deploy:
        edge: true
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        cleanup: false
